[package]
name = "helios-verifiable-api-types"
version.workspace = true
edition = "2021"

[dependencies]
alloy = { workspace = true, features = ["trie"] }
serde.workspace = true
serde_json.workspace = true

# self crates
helios-common = { path = "../../common" }
