[package]
name = "helios-ts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.33"
wasm-bindgen-test = "0.3.0"
serde-wasm-bindgen = "0.4.5"
console_error_panic_hook = "0.1.7"

eyre.workspace = true

ethers = "2.0.2"
hex = "0.4.3"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.85"

client = { path = "../client" }
common = { path = "../common" }
consensus = { path = "../consensus" }
execution = { path = "../execution" }
config = { path = "../config" }


[dependencies.web-sys]
version = "0.3"
features = ["console", "Storage", "Window"]
