[package]
name = "helios-ts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
console_error_panic_hook = "0.1.7"

ethers = "1.0.0"
hex = "0.4.3"

consensus = { path = "../consensus" }
execution = { path = "../execution" }
config = { path = "../config" }

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]
