[package]
name = "common"
version = "0.5.3"
edition = "2021"

[dependencies]
eyre.workspace = true
serde.workspace = true
hex.workspace = true
ssz-rs.workspace = true
ethers.workspace = true
thiserror.workspace = true
