[package]
name = "consensus"
version = "0.1.3"
edition = "2021"

[dependencies]
# tokio = { version = "1", features = ["full"] }
eyre = "0.6.8"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.85"
hex = "0.4.3"
ssz-rs = { git = "https://github.com/ralexstokes/ssz-rs" }
blst = "0.3.10"
ethers = "1.0.2"
bytes = "1.2.1"
toml = "0.5.9"
async-trait = "0.1.57"
log = "0.4.17"
chrono = "0.4.22"
thiserror = "1.0.37"
# openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.11.13", features = ["json"] }

common = { path = "../common" }
config = { path = "../config" }
